# Generated by Django 6.0.5 on 2026-08-17 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_author_alter_article_category_and_more"),
        ("forum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pinnedpost",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="thread",
            name="article",
            field=models.ForeignKey(
                blank=True,
                help_text="Articolo da cui nasce la discussione, se presente.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="threads",
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="threads",
                to="forum.forumcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["thread", "created_at"], name="forum_post_thread__a619d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["-is_pinned", "-updated_at"],
                name="forum_threa_is_pinn_df8c45_idx",
            ),
        ),
    ]
