# Generated by Django 6.0.5 on 2026-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="moderation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="muted_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
